### PR TITLE
Add space on focus option

### PR DESCRIPTION
**Pull request by unstablectrl**
When focusing the search box my intuition is that I would just have the cursor at the end of the search query that I just made but this isn't what happens, a space is added.

This is probably a personal preference thing so I wanted to include this as an option.

The repository didn't have any `CONTRIBUTING.md` guidelines so I just winged it and also went ahead and also added to the change log and version on the `manifest.json`.

### CODE REVIEW

**Comment by OskarNS** [comment]
Huge thumbs up for this! 👍

**Comment by unstablectrl** [comment]
Too old

**Comment by OskarNS** [comment]
@unstablectrl 😥😥😥

**Comment by jchafik** [comment]
Thanks for the PR @unstablectrl. I've merged your change and pushed it to the Chrome store. It should be available shortly.

**Pull request merged**
